//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMP_agent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SNMP_agent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.6.1.2.1.1 - system
        ///1.3.6.1.2.1.1.1 - sysDescr
        ///1.3.6.1.2.1.1.2 - sysObjectID
        ///1.3.6.1.2.1.1.3 - sysUpTime
        ///1.3.6.1.2.1.1.4 - sysContact
        ///1.3.6.1.2.1.1.5 - sysName
        ///1.3.6.1.2.1.1.6 - sysLocation
        ///1.3.6.1.2.1.1.7 - sysServices
        ///1.3.6.1.2.1.2 - interfaces
        ///1.3.6.1.2.1.2.1 - ifNumber
        ///1.3.6.1.2.1.2.2 - ifTable
        ///1.3.6.1.2.1.2.2.1 - ifEntry
        ///1.3.6.1.2.1.2.2.1.1 - ifIndex
        ///1.3.6.1.2.1.2.2.1.2 - ifDescr
        ///1.3.6.1.2.1.2.2.1.3 - ifType
        ///1.3.6.1.2.1.2.2.1.4 - ifMtu
        ///1.3.6.1.2.1.2.2.1.5 - ifSpeed
        ///1.3.6.1.2.1.2.2.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mibTreeElements {
            get {
                return ResourceManager.GetString("mibTreeElements", resourceCulture);
            }
        }
    }
}
