//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnmpService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SnmpTypeObject", Namespace="http://schemas.datacontract.org/2004/07/SnmpService")]
    public partial class SnmpTypeObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string OidField;
        
        private string TypeField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oid
        {
            get
            {
                return this.OidField;
            }
            set
            {
                this.OidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISnmpService")]
public interface ISnmpService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnmpService/Get", ReplyAction="http://tempuri.org/ISnmpService/GetResponse")]
    SnmpService.SnmpTypeObject Get(SnmpService.SnmpTypeObject snmpObject);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnmpService/Get", ReplyAction="http://tempuri.org/ISnmpService/GetResponse")]
    System.Threading.Tasks.Task<SnmpService.SnmpTypeObject> GetAsync(SnmpService.SnmpTypeObject snmpObject);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnmpService/GetString", ReplyAction="http://tempuri.org/ISnmpService/GetStringResponse")]
    string GetString(string oid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnmpService/GetString", ReplyAction="http://tempuri.org/ISnmpService/GetStringResponse")]
    System.Threading.Tasks.Task<string> GetStringAsync(string oid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnmpService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISnmpService/GetDataUsingDataContractResponse")]
    SnmpService.SnmpTypeObject GetDataUsingDataContract(SnmpService.SnmpTypeObject snmp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISnmpService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISnmpService/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<SnmpService.SnmpTypeObject> GetDataUsingDataContractAsync(SnmpService.SnmpTypeObject snmp);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISnmpServiceChannel : ISnmpService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SnmpServiceClient : System.ServiceModel.ClientBase<ISnmpService>, ISnmpService
{
    
    public SnmpServiceClient()
    {
    }
    
    public SnmpServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SnmpServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SnmpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SnmpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public SnmpService.SnmpTypeObject Get(SnmpService.SnmpTypeObject snmpObject)
    {
        return base.Channel.Get(snmpObject);
    }
    
    public System.Threading.Tasks.Task<SnmpService.SnmpTypeObject> GetAsync(SnmpService.SnmpTypeObject snmpObject)
    {
        return base.Channel.GetAsync(snmpObject);
    }
    
    public string GetString(string oid)
    {
        return base.Channel.GetString(oid);
    }
    
    public System.Threading.Tasks.Task<string> GetStringAsync(string oid)
    {
        return base.Channel.GetStringAsync(oid);
    }
    
    public SnmpService.SnmpTypeObject GetDataUsingDataContract(SnmpService.SnmpTypeObject snmp)
    {
        return base.Channel.GetDataUsingDataContract(snmp);
    }
    
    public System.Threading.Tasks.Task<SnmpService.SnmpTypeObject> GetDataUsingDataContractAsync(SnmpService.SnmpTypeObject snmp)
    {
        return base.Channel.GetDataUsingDataContractAsync(snmp);
    }
}
